# Generated by Django 4.2.6 on 2023-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_alter_depositoptions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate2',
            field=models.FloatField(default=-1),
        ),
    ]
