# Generated by Django 4.2.2 on 2023-09-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurent',
        ),
    ]
