# Generated by Django 4.2.4 on 2023-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='korean_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
