# Generated by Django 4.2.4 on 2023-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_financial_products_user_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('year', models.TextField()),
                ('salary_level', models.IntegerField()),
            ],
        ),
    ]
