# Generated by Django 4.2.4 on 2023-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='dcls_end_day',
            field=models.TextField(null=True),
        ),
    ]
