# Generated by Django 4.2.4 on 2023-11-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_alter_depositproducts_dcls_end_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.depositproducts', to_field='fin_prdt_cd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_products', through='finance.LikeProducts', to=settings.AUTH_USER_MODEL),
        ),
    ]
